int score = 0; 
int command = 0; 
int width = 0; 
int height = 0; 
int vertical_position = 0, horizontal_position = 0;
int fire_direction = 0;
int show_fire = 0;
int show_debug = 0;
int jitter = 2;
int rander = 0;
int spawn_pad = 15;
int number_of_enemies = 5;
int number_of_rocks = 25;
int enemies[100][4];
int rocks[100][4];
int rock[2];

void render();

int random_number(int min_num, int max_num, int modifier);
void respawn_enemy(int enemy);
void perform_action(int c);
void move_enemies();
int death();
void build_enemies();
void build_rocks();
void reset();
void change_level();
int in_box(int enemy);
int rock_present(int x, int y);
int on_rock(int ver_pos, int hor_pos);
